apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-app
  namespace: aiops-banco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aiops
  template:
    metadata:
      labels:
        app: aiops
    spec:
      containers:
        - name: aiops-app
          image: marcia/aiops-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

