apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-servicemonitor
  namespace: aiops-banco
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: aiops   
  namespaceSelector:
    matchNames:
      - aiops-banco
  endpoints:
    - port: http   
      path: /metrics
      interval: 5s

